/** @type {import('tailwindcss').Config} */
export default {
	content: ["./index.jsx", "./index.html"],
	safelist: [
		// Try generating all common Tailwind utilities
		"px-12",
		"py-2",
		"bg-blue-500",
		"text-white",
		"rounded",
		"hover:bg-blue-600",
		"p-5",
		"min-h-screen",
		"flex",
		"items-center",
		"justify-center",
		"font-sans",
		"fixed",
		"bottom-2",
		"right-2",
		"bg-black",
		"bg-opacity-70",
		"px-2",
		"py-1",
		"text-xs",
		"font-mono",
		// Add more comprehensive coverage
		...Array.from({ length: 100 }, (_, i) => `px-${i}`),
		...Array.from({ length: 100 }, (_, i) => `py-${i}`),
		...Array.from({ length: 100 }, (_, i) => `p-${i}`),
		...Array.from({ length: 100 }, (_, i) => `m-${i}`),
		"bg-blue-100",
		"bg-blue-200",
		"bg-blue-300",
		"bg-blue-400",
		"bg-blue-500",
		"bg-blue-600",
		"bg-blue-700",
		"bg-blue-800",
		"bg-blue-900",
		"hover:bg-blue-100",
		"hover:bg-blue-200",
		"hover:bg-blue-300",
		"hover:bg-blue-400",
		"hover:bg-blue-500",
		"hover:bg-blue-600",
		"hover:bg-blue-700",
		"hover:bg-blue-800",
		"hover:bg-blue-900",
		"text-white",
		"text-black",
		"text-gray-100",
		"text-gray-200",
		"text-gray-300",
		"text-gray-400",
		"text-gray-500",
		"text-gray-600",
		"text-gray-700",
		"text-gray-800",
		"text-gray-900",
		"rounded",
		"rounded-sm",
		"rounded-md",
		"rounded-lg",
		"rounded-xl",
		"rounded-2xl",
		"rounded-3xl",
		"rounded-full",
	],
	theme: {
		extend: {},
	},
	plugins: [],
}
